name: multiservicios_tun
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  intl: ^0.17.0
  substring_highlight: ^1.0.33
  fluttertoast: ^8.0.7
  email_validator: ^2.0.1
  flutter_bloc: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'images/logov1.png'
  adaptive_icon_background: 'images/logov1.png'

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/data.json